### ISSUE TITLE
disabled-worlds.invert doesn't work on 1.16.5

### ISSUE THREAD

**Issue by adiantek** [ItsLewizzz/DeluxeHub#94]
setting disabled-worlds.invert on 1.16.5 to true makes plugin impossible to start:

```
[01:02:55.028] [Server thread/ERROR]: Error occurred while enabling DeluxeHub v3.5.4 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/generator/WorldInfo
        at fun.lewisdev.deluxehub.module.ModuleManager.loadModules(ModuleManager.java:44) ~[?:?]
        at fun.lewisdev.deluxehub.DeluxeHubPlugin.onEnable(DeluxeHubPlugin.java:95) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paper-1.16.5.jar:git-Paper-"fa1a7c180"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-1.16.5.jar:git-Paper-"fa1a7c180"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-1.16.5.jar:git-Paper-"fa1a7c180"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[paper-1.16.5.jar:git-Paper-"fa1a7c180"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[paper-1.16.5.jar:git-Paper-"fa1a7c180"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[paper-1.16.5.jar:git-Paper-"fa1a7c180"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[paper-1.16.5.jar:git-Paper-"fa1a7c180"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[paper-1.16.5.jar:git-Paper-"fa1a7c180"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[paper-1.16.5.jar:git-Paper-"fa1a7c180"]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.generator.WorldInfo
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-1.16.5.jar:git-Paper-"fa1a7c180"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[paper-1.16.5.jar:git-Paper-"fa1a7c180"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more
```

You're calling World.getName(), which doesn't work, bcuz on 1.20.1 it's in WorldInfo:
https://github.com/ItsLewizzz/DeluxeHub/blob/master/src/main/java/fun/lewisdev/deluxehub/module/ModuleManager.java#L44
